### ISSUE TITLE
where is the sqlite file ?

### ISSUE THREAD

**Issue by akteruzzaman816** [BuddhiEash/simple-pharmacy-management-system-laravel#1]
it's getting error for the db file

![image](https://github.com/BuddhiEash/simple-pharmacy-management-system-laravel/assets/18428033/2b8bfd28-5a14-441d-b017-876e13fc605f)

**Comment by BuddhiEash** [comment]
It's not a good practice to include the database file in the source code, and that's why I didn't include the SQLite file. 

I have added already migrations and seeders. 

So you can create an empty sqlite database file called "database.sqlite" under "database/".

Finally, run `php artisan migrate --seed`

Cheers!

**Comment by akteruzzaman816** [comment]
Thanks man 😊
